### ISSUE TITLE
Can't seem to run it :(

### ISSUE THREAD

**Issue by dkowis** [Microsoft/mvnfeed-cli#13]
I use [rtx](https://github.com/jdx/rtx) to manage my python environments, and I have the latest python3 installed, and yet, for some reason it doesn't run:

```
❯ mvnfeed -h
Traceback (most recent call last):
  File "/Users/Me/.local/share/rtx/installs/python/3.11.5/bin/mvnfeed", line 5, in <module>
    from mvnfeed.cli.__main__ import main
  File "/Users/Me/gitwork/mvnfeed-cli/src/mvnfeed-cli/mvnfeed/cli/__main__.py", line 8, in <module>
    from .mvnfeed_cli import MvnFeedCLI
  File "/Users/Me/gitwork/mvnfeed-cli/src/mvnfeed-cli/mvnfeed/cli/mvnfeed_cli.py", line 4, in <module>
    from mvnfeed.cli.common.config import GLOBAL_CONFIG_DIR, CLI_ENV_VARIABLE_PREFIX, load_config
ModuleNotFoundError: No module named 'mvnfeed.cli.common'
```
I don't use a lot of python things by hand, so I don't know what I'd need to do to make it work.

**Comment by dkowis** [comment]
My next step was to use a docker image, to avoid any fancy macbook problems or anything like that

```Dockerfile
FROM --platform=arm64 python:3-bookworm

RUN mkdir /opt/app
WORKDIR /opt/app

COPY . /opt/app
RUN python scripts/dev_setup.py \
  && mvnfeed -h

```

Sadly, this didn't work either. Different errors:

```
 => ERROR [6/6] RUN python scripts/dev_setup.py   && mvnfeed -h                                                                                                               3.4s
------
 > [6/6] RUN python scripts/dev_setup.py   && mvnfeed -h:
1.139 Obtaining file:///opt/app/src/mvnfeed_modules/mvnfeed-cli-common
1.139   Preparing metadata (setup.py): started
1.418   Preparing metadata (setup.py): finished with status 'done'
1.420 Obtaining file:///opt/app/src/mvnfeed_modules/mvnfeed-cli-transfer
1.421   Preparing metadata (setup.py): started
1.536   Preparing metadata (setup.py): finished with status 'done'
1.539 Obtaining file:///opt/app/src/mvnfeed-cli
1.539   Preparing metadata (setup.py): started
1.656   Preparing metadata (setup.py): finished with status 'done'
1.726 Collecting knack==0.5.1 (from mvnfeed-cli-common==0.0.1)
1.797   Downloading knack-0.5.1-py2.py3-none-any.whl (50 kB)
1.805      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 6.5 MB/s eta 0:00:00
1.830 Collecting argcomplete (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
1.830   Obtaining dependency information for argcomplete from https://files.pythonhosted.org/packages/4f/ef/8b604222ba5e5190e25851aa3a5b754f2002361dc62a258a8e9f13e866f4/argcomplete-3.1.1-py3-none-any.whl.metadata
1.839   Downloading argcomplete-3.1.1-py3-none-any.whl.metadata (16 kB)
1.859 Collecting colorama (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
1.866   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
1.886 Collecting jmespath (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
1.895   Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
1.919 Collecting pygments (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
1.919   Obtaining dependency information for pygments from https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl.metadata
1.926   Downloading Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
1.961 Collecting pyyaml (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
1.961   Obtaining dependency information for pyyaml from https://files.pythonhosted.org/packages/5e/94/7d5ee059dfb92ca9e62f4057dcdec9ac08a9e42679644854dc01177f8145/PyYAML-6.0.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
1.969   Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (2.1 kB)
1.982 Collecting six (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
1.989   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
2.002 Collecting tabulate (from knack==0.5.1->mvnfeed-cli-common==0.0.1)
2.008   Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
2.029 Downloading argcomplete-3.1.1-py3-none-any.whl (41 kB)
2.032    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 kB 16.6 MB/s eta 0:00:00
2.042 Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)
2.065    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 54.5 MB/s eta 0:00:00
2.077 Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (732 kB)
2.087    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 732.2/732.2 kB 88.9 MB/s eta 0:00:00
2.126 Installing collected packages: tabulate, six, pyyaml, pygments, jmespath, colorama, argcomplete, knack, mvnfeed-cli-transfer, mvnfeed-cli-common, mvnfeed-cli
2.589   Running setup.py develop for mvnfeed-cli-transfer
2.771   Running setup.py develop for mvnfeed-cli-common
2.917   Running setup.py develop for mvnfeed-cli
3.088 Successfully installed argcomplete-3.1.1 colorama-0.4.6 jmespath-1.0.1 knack-0.5.1 mvnfeed-cli-0.0.1 mvnfeed-cli-common-0.0.1 mvnfeed-cli-transfer-0.0.1 pygments-2.16.1 pyyaml-6.0.1 six-1.16.0 tabulate-0.9.0
3.088 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
3.252 Executing: /usr/local/bin/python -m pip install -e src/mvnfeed_modules/mvnfeed-cli-common -e src/mvnfeed_modules/mvnfeed-cli-transfer -e src/mvnfeed-cli
3.252
3.350 ERROR: load() missing 1 required positional argument: 'Loader'
3.350 Traceback (most recent call last):
3.350   File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 206, in invoke
3.350     cmd_result = self.invocation.execute(args)
3.350                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/site-packages/knack/invocation.py", line 153, in execute
3.350     parsed_args = self.parser.parse_args(args)
3.350                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/argparse.py", line 1869, in parse_args
3.350     args, argv = self.parse_known_args(args, namespace)
3.350                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/argparse.py", line 1902, in parse_known_args
3.350     namespace, args = self._parse_known_args(args, namespace)
3.350                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/argparse.py", line 2114, in _parse_known_args
3.350     start_index = consume_optional(start_index)
3.350                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/argparse.py", line 2054, in consume_optional
3.350     take_action(action, args, option_string)
3.350   File "/usr/local/lib/python3.11/argparse.py", line 1978, in take_action
3.350     action(self, namespace, argument_values, option_string)
3.350   File "/usr/local/lib/python3.11/argparse.py", line 1119, in __call__
3.350     parser.print_help()
3.350   File "/usr/local/lib/python3.11/argparse.py", line 2601, in print_help
3.350     self._print_message(self.format_help(), file)
3.350                         ^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/site-packages/knack/parser.py", line 222, in format_help
3.350     self.cli_help.show_help(self.prog.split()[0],
3.350   File "/usr/local/lib/python3.11/site-packages/knack/help.py", line 664, in show_help
3.350     else self.group_help_cls(self, delimiters, parser)
3.350          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/site-packages/knack/help.py", line 219, in __init__
3.350     child.load(options)
3.350   File "/usr/local/lib/python3.11/site-packages/knack/help.py", line 178, in load
3.350     self._load_from_file()
3.350   File "/usr/local/lib/python3.11/site-packages/knack/help.py", line 181, in _load_from_file
3.350     file_data = _load_help_file(self.delimiters)
3.350                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350   File "/usr/local/lib/python3.11/site-packages/knack/help_files.py", line 14, in _load_help_file
3.350     return yaml.load(helps[delimiters])
3.350            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.350 TypeError: load() missing 1 required positional argument: 'Loader'
------
Dockerfile:8
--------------------
   7 |     RUN ls
   8 | >>> RUN python scripts/dev_setup.py \
   9 | >>>   && mvnfeed -h
  10 |
--------------------
ERROR: failed to solve: process "/bin/sh -c python scripts/dev_setup.py   && mvnfeed -h" did not complete successfully: exit code: 1
```

**Comment by dkowis** [comment]
The second error seems to be that the pyyaml is too new, for some reason for this repo: 

https://stackoverflow.com/a/69565230/423218

**Comment by dkowis** [comment]
Okay through a pile of google searching and wonderful python dependency problems: 

```Dockerfile
FROM --platform=arm64 python:3-bookworm

RUN mkdir /opt/app
WORKDIR /opt/app

# Have to use older pyyaml than the container provides
# https://github.com/yaml/pyyaml/issues/601#issuecomment-1693730229
RUN pip install "Cython<3.0" pyyaml==5.4.1 --no-build-isolation

COPY . /opt/app
RUN python3 scripts/dev_setup.py \
  && mvnfeed -h

```

This works, and I can run it from docker, I'll see if this will still work locally.

**Comment by dkowis** [comment]
Nope, I still have the problem with "No module named 'mvnfeed.cli.common'"

**Comment by proofrock** [comment]
Same problem here. Thanks for the dockerfile! Maybe it will be useful for someone passing by, I build and run it with

```bash
docker buildx build . -t my-mvnfeed-cli
docker run -it my-mvnfeed-cli /bin/bash
```

Also, your Dockerfile is for arm64 (I suppose that's your arch, but it may be worth noting for anyone else reading this)
