### ISSUE TITLE
transfer fails with No module named 'requests'

### ISSUE THREAD

**Issue by mb345345** [Microsoft/mvnfeed-cli#9]
it has installed no worries, added repos to the config, and then tried the transfer. it's between 2 az artifact feeds. Wondering if it's the version of python I'm using? (Python 3.9.0)

Thanks for your time :)

mvnfeed artifact transfer \
    --from=[REPO_NAME] \
    --to=[REPO_NAME] \
    --name=[GROUP_ID]:[ARTIFACT_ID]:[VERSION] \
    --transfer_deps

No module named 'requests'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Python39\lib\site-packages\knack\invocation.py", line 134, in execute
    self.commands_loader.load_arguments(command)
  File "c:\dev\projects\mvnfeed-cli\src\mvnfeed-cli\mvnfeed\cli\mvnfeed_commands.py", line 13, in load_arguments
    super(MvnFeedCommandsLoader, self).load_arguments(command)
  File "C:\Python39\lib\site-packages\knack\commands.py", line 181, in load_arguments
    self.command_table[command].load_arguments()
  File "C:\Python39\lib\site-packages\knack\commands.py", line 76, in load_arguments
    cmd_args = self.arguments_loader()
  File "C:\Python39\lib\site-packages\knack\commands.py", line 216, in arguments_loader
    return list(extract_args_from_signature(CLICommandsLoader._get_op_handler(operation),
  File "C:\Python39\lib\site-packages\knack\commands.py", line 233, in _get_op_handler
    op = import_module(mod_to_import)
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\dev\projects\mvnfeed-cli\src\mvnfeed_modules\mvnfeed-cli-transfer\mvnfeed\cli\transfer\transfer.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by easterapps** [comment]
Install the missing module manually
`python3 -m pip install requests --user`
